DMSApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Your URL patterns
    path('auth/login/',  views.LoginView.as_view(), name='masuk'),
    path('auth/logout/', views.LogoutView.as_view(), name='keluar'),
    # path('auth/logout/', LogoutView.as_view(), name='keluar'),
    # path('login/', LoginView.as_view(template_name='DMSApp/Komponen/login.html'), name='login'),
    path('', views.DashboardView.as_view(), name='dashboard_view'),

    path('account/page/', views.AkunListView.as_view(), name='akun_view'),
    path('account/update/<str:pk>/', views.AkunUpdateView.as_view(), name='akun_update'),
    path('account/register/', views.AkunRegisterView.as_view(), name='akun_regist_view'),
    path('acount/activation/<str:pk>/', views.AkunActivateDeactivateView.as_view(), name='akun_is_active'),
    path('account/delete/<str:pk>/', views.AkunDeleteView.as_view(), name='akun_is_delete'),

    path('department/page/', views.DepartemenListView.as_view(), name='departemen_view'),
    path('department/update/<str:pk>/', views.DepartemenUpdateView.as_view(), name='departemen_update'),
    path('department/activation/<str:pk>/', views.DepartemenActivateDeactivateView.as_view(), name='departemen_is_active'),
    path('department/delete/<str:pk>/', views.DepartemenDeleteView.as_view(), name='departemen_is_delete'),

    path('category/page/', views.KategoriDokumenListView.as_view(), name='kategori_dokumen_view'),
    path('category/update/<str:pk>/', views.KategoriDokumenUpdateView.as_view(), name='kategori_dokumen_update'),
    path('category/activation/<str:pk>/', views.KategoriDokumenActivateDeactivateView.as_view(), name='kategori_dokumen_is_active'),
    path('category/delete/<str:pk>/', views.KategoriDokumenDeleteView.as_view(), name='kategori_dokumen_is_delete'),

    path('document/view/', views.DokumenListView.as_view(), name='dokumen_view'),
    path('document/create/', views.DokumenCreateView.as_view(), name='dokumen_create'),
    path('document/list-view/', views.DokumenNumberListView.as_view(), name='dokumen_list_view'),
    path('document/update/<str:pk>/', views.DokumenUpdateView.as_view(), name='dokumen_update'),
    path('document/delete/<str:pk>/', views.DokumenDeleteView.as_view(), name='dokumen_is_delete'),
    path('document/detail/<str:pk>/', views.DokumenDetailView.as_view(), name='dokumen_detail'),
    path('document/update-status/<str:pk>/', views.DokumenUpdateStatusView.as_view(), name='dokumen_status_update'),
    path('document/activation/<str:pk>/', views.DokumenActivateDeactivateView.as_view(), name='dokumen_is_active')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DMSProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DMSApp.urls'))
]

DMSApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import os
    
# Create your models here.
class Departemen(models.Model):
    department = models.CharField(max_length=100, null=True)
    department_code = models.CharField(max_length=10, blank=True)
    company = models.CharField(max_length=100, blank=True)
    address = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    related_category = models.ManyToManyField('KategoriDokumen')

    def __str__(self):
        return self.department


class UserDetail(AbstractUser):
    user_department = models.ForeignKey(Departemen, on_delete=models.CASCADE, null=True)
    # ldap_department = models.CharField(max_length=100, null=True)
    is_approver = models.BooleanField(default=False)
    is_releaser = models.BooleanField(default=False)
    is_uploader = models.BooleanField(default=False)
    is_ldap = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    ''' 
    @staticmethod
    def extract_ou_from_dn(dn):
        parts = dn.split(',')
        for part in parts:
            if part.startswith('OU='):
                return part[3:]
        return None

    def save(self, *args, **kwargs):
        if self.distinguishedName:
            department_name = self.extract_ou_from_dn(self.distinguishedName)
            if department_name:
                department, created = Departemen.objects.get_or_create(department=department_name)
                self.parent_department = department
        super(UserDetail, self).save(*args, **kwargs)
    '''

    
class KategoriDokumen(models.Model):
    category = models.CharField(max_length=100, null=True)
    category_initial = models.CharField(max_length=10, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    related_label = models.ManyToManyField('KategoriDokumenLabel')

    def __str__(self):
        return self.category

class KategoriDokumenLabel(models.Model):
    name = models.CharField(max_length=100)

class Dokumen(models.Model):
    parent_category = models.ForeignKey(KategoriDokumen, on_delete=models.CASCADE)
    parent_department = models.ForeignKey(Departemen, on_delete=models.CASCADE)
    form_no = models.CharField(max_length=100, null=True)
    document_no = models.CharField(max_length=100, null=True)
    sub_document_no = models.CharField(max_length=100, null=True)
    document_name = models.CharField(max_length=100, null=True)
    effective_date = models.DateTimeField(null=True)
    revision_no = models.CharField(max_length=100, null=True)
    revision_date = models.DateTimeField(null=True)
    part_no = models.CharField(max_length=100, null=True)
    part_name = models.CharField(max_length=100, null=True)
    supplier_name = models.CharField(max_length=100, null=True)
    customer_name = models.CharField(max_length=100, null=True)
    # status
    is_active = models.BooleanField(default=True)
    is_inprogress = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    is_released = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    
    pdf_file = models.FileField(null=True, storage=None) 
    sheet_file = models.FileField(null=True, storage=None)
    other_file = models.FileField(null=True, storage=None)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    modified_date = models.DateTimeField(auto_now=True, null=True)

'''class Notifikasi(models.Model):
    dokumen = models.ForeignKey(Dokumen, on_delete=models.CASCADE, null=True)
    lampiran = models.FileField(null=True, storage=None)
    is_active = models.BooleanField(default=True)'''

class LogNotifikasi(models.Model):
    time_stamp = models.DateTimeField(auto_now_add=True, null=True)
    parent_user = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    parent_document = models.ForeignKey(Dokumen, on_delete=models.CASCADE)
    action = models.CharField(max_length=100, null=True)
    reason = models.TextField(blank=True)

DMSApp/views.py
from itertools import chain
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DeleteView, DetailView, View
from .models import UserDetail, Departemen, KategoriDokumen, KategoriDokumenLabel, Dokumen, LogNotifikasi
from django.conf import settings
from urllib.parse import urljoin
import os, shutil
from django import forms
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import PermissionDenied, ValidationError
from django.urls import reverse
from django.db.models import Count, Max
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout, authenticate
import ldap
from django_auth_ldap.backend import LDAPBackend
from django.utils.text import slugify
from .templatetags.custom_filters import custom_slugify  # import the custom filter


folder_target = 'media/DMSApp/'

daftar_label = [{'form_no': {"label": "Form Number", "type": "text"},
                'document_no': {"label": "Document ID", "type": "text"},
                'document_name': {"label": "Document Title", "type": "text"},
                'effective_date': {"label": "Effective Date", "type": "date"},
                'revision_no': {"label": "Revision No", "type": "text"},
                'revision_date': {"label": "Revision Date", "type": "date"},
                'part_no': {"label": "Part Number", "type": "text"},
                'part_name': {"label": "Part Name", "type": "text"},
                'supplier_name': {"label": "Supplier Name", "type": "text"},
                'customer_name': {"label": "Customer Name", "type": "text"},
                'pdf_file': {"label": "PDF File", "type": "file", "extension": ".pdf"},
                'sheet_file': {"label": "Sheet File", "type": "file", "extension": ".ods, .xlsx"},
                'other_file': {"label": "Additional File", "type": "file"}
                }]


'''
class LDAPUsernameForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)

# Create your views here.
class LoginView(FormView):
    template_name = 'DMSApp/Komponen/login.html'
    form_class = LDAPUsernameForm

    def form_valid(self, form):
        username = form.cleaned_data['username']
        
        # LDAP settings
        LDAP_SERVER_URI = settings.AUTH_LDAP_SERVER_URI
        BIND_DN = settings.AUTH_LDAP_BIND_DN
        BIND_PASSWORD = settings.AUTH_LDAP_BIND_PASSWORD
        USER_SEARCH_BASE = "ou=Departments,dc=fln,dc=local"
        SEARCH_FILTER = "(sAMAccountName=%(user)s)"  # Filter for sAMAccountName
        
        try:
            # Initialize LDAP connection
            conn = ldap.initialize(LDAP_SERVER_URI)
            conn.simple_bind_s(BIND_DN, BIND_PASSWORD)
            
            # Search for the user
            result = conn.search_s(USER_SEARCH_BASE, ldap.SCOPE_SUBTREE, SEARCH_FILTER % {'user': username})
            
            if result:
                # User found in LDAP
                return render(self.request, 'DMSApp/Komponen/dashboard.html', {'username': username})
            else:
                # User not found in LDAP
                return render(self.request, 'ldap_username_invalid.html', {'username': username})
        
        except ldap.LDAPError as e:
            # LDAP connection or search error
            return render(self.request, 'ldap_error.html', {'error_message': f"LDAP search failed: {e}"})

'''


class LoginView(LoginView):
    template_name = 'DMSApp/Komponen/login.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and self.request.user.is_active:
            return redirect('/')  # Redirect to the home page if already authenticated
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        # First try LDAP authentication
        ldap_backend = LDAPBackend()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = None
        try:
            user = ldap_backend.authenticate(self.request, username=username, password=password)
        except ldap.LDAPError as e:
            print(f"LDAP authentication error: {e}")
            pass

        # If LDAP authentication fails, fall back to the default model backend
        if user is None:
            user = authenticate(self.request, username=username, password=password)

        if user is not None:
            login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect(self.get_success_url())
        else:
            # Optionally, you can log the failure reason or take some other action
            return self.form_invalid(form)
        

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)
    
class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'DMSApp/Komponen/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        for label_dict in daftar_label:
            context['list_label'] = label_dict
        dokumen_list = Dokumen.objects.filter(is_active=True, is_approved=True).order_by('document_no','-revision_no')

        # Use Python to filter out duplicates based on document_no
        unique_dokumen_list = []
        seen_document_nos = set()
        for dokumen in dokumen_list:
            if dokumen.document_no not in seen_document_nos:
                unique_dokumen_list.append(dokumen)
                seen_document_nos.add(dokumen.document_no)
        context['dokumen_list'] = unique_dokumen_list

        '''
        # LDAP search details
        LDAP_SERVER_URI = settings.AUTH_LDAP_SERVER_URI
        BIND_DN = settings.AUTH_LDAP_BIND_DN
        BIND_PASSWORD = settings.AUTH_LDAP_BIND_PASSWORD
        USER_SEARCH_BASE = "ou=Departments,dc=fln,dc=local"
        SEARCH_FILTER = "(objectClass=person)"  # Fetch all users

        # Perform LDAP search
        try:
            conn = ldap.initialize(LDAP_SERVER_URI)
            conn.simple_bind_s(BIND_DN, BIND_PASSWORD)
            result = conn.search_s(USER_SEARCH_BASE, ldap.SCOPE_SUBTREE, SEARCH_FILTER)
            
            # Pass the search result to the context
            context['ldap_results'] = result
        except ldap.LDAPError as e:
            context['ldap_error'] = f"LDAP search failed: {e}"    
        '''
            
        '''
        # LDAP search details
        LDAP_SERVER_URI = settings.AUTH_LDAP_SERVER_URI
        BIND_DN = settings.AUTH_LDAP_BIND_DN
        BIND_PASSWORD = settings.AUTH_LDAP_BIND_PASSWORD
        USER_SEARCH_BASE = "ou=Departments,dc=fln,dc=local"
        SEARCH_FILTER = "(objectClass=user)"  # Filter for user objects

        # Attributes to retrieve
        ATTRIBUTES = ['sAMAccountName']

        # Perform LDAP search
        try:
            conn = ldap.initialize(LDAP_SERVER_URI)
            conn.simple_bind_s(BIND_DN, BIND_PASSWORD)
            result = conn.search_s(USER_SEARCH_BASE, ldap.SCOPE_SUBTREE, SEARCH_FILTER, ATTRIBUTES)
            
            # Extract sAMAccountName and pass to context
            account_names = []
            for dn, entry in result:
                if 'sAMAccountName' in entry:
                    account_names.append(entry['sAMAccountName'][0].decode('utf-8'))
            
            # Pass the account names to the context
            context['account_names'] = account_names
        except ldap.LDAPError as e:
            context['ldap_error'] = f"LDAP search failed: {e}"
            
        '''

        return context
    
class AkunRegisterView(CreateView):
    model = UserDetail
    template_name = 'DMSApp/CrudAkun/register.html'
    fields = ['username', 'first_name', 'last_name', 'email', 'password']
    success_url = '/account/page/'

    def form_valid(self, form):
        if self.request.user.is_superuser or not UserDetail.objects.filter(is_superuser=True, is_active=True):
            password = form.cleaned_data['password']
            confirm_password = self.request.POST.get('password2')

            # Check if passwords match
            if password == confirm_password:
                # Hash the password before saving
                form.instance.set_password(form.cleaned_data['password'])
                form.instance.is_ldap = False

                # if superuser not exist
                if not UserDetail.objects.filter(is_superuser=True, is_active=True):
                    form.instance.is_superuser = True
                    self.object = form.save()
                    # if form.cleaned_data.get('username'):
                    # return redirect('/')self.success_url
                    return redirect(self.success_url)
            else:
                return redirect(self.request.META.get('HTTP_REFERER'))
            
            return super().form_valid(form)
        else:
            raise PermissionDenied("Cannot update this account because it is a superuser.")
        

class AkunListView(LoginRequiredMixin, CreateView, ListView): # CreateView as Update in modal
    model = UserDetail
    template_name = 'DMSApp/CrudAkun/view.html'
    context_object_name = 'user_list'  # For ListView
    fields = ['user_department', 'first_name', 'last_name' , 'email', 'is_uploader', 'is_releaser', 'is_approver', 'is_superuser' ]

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Check if the user is a superuser
        if not self.request.user.is_superuser:
            # List of fields to remove
            fields_to_remove = ['first_name', 'last_name', 'email', 'is_superuser']
            for field in fields_to_remove:
                form.fields.pop(field, None)
        return form
    
    def get_context_data(self, **kwargs):

templates/DMSApp/CrudArsip/create.html
{% load static %}
{% load custom_filters %}

{% include 'DMSApp/Komponen/navbar.html' %}
<!-- partial -->
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">Document Management System</h3>
            <nav aria-label="breadcrumb rounded-0">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">Document</li>
                {% if nm_departemen %}
                <li class="breadcrumb-item active" aria-current="page">{{ nm_departemen|capfirst }}</li>
                {% endif %}
                <li class="breadcrumb-item active" aria-current="page">{% if nm_dokumen %}<a href='{% url 'arsip_view' %}?dept={{ nm_departemen|custom_slugify }}'>{% endif %}Category</a></li>
                {% if nm_dokumen %}
                <li class="breadcrumb-item active" aria-current="page">{% if nm_dokumen %}<a href='{% url 'arsip_view' %}?menu={{ nm_dokumen|custom_slugify }}&dept={{ nm_departemen|custom_slugify }}'>{% endif %}{{ nm_dokumen|capfirst }}</a></li>
                {% endif %}
                {% if nm_arsip %}
                <li class="breadcrumb-item active" aria-current="page">{% if nm_dokumen %}<a href='{% url 'arsip_list_detail' %}?menu={{ nm_dokumen|custom_slugify }}&dept={{ nm_departemen|custom_slugify }}&archive={{ nm_arsip|custom_slugify }}'>{% endif %}{{ nm_arsip|capfirst }}</a></li>
                <li class="breadcrumb-item active">{{ kode_arsip }}</li>
                <li class="breadcrumb-item active">Revision</li>
                {% else %}
                <li class="breadcrumb-item active">Register</li> {{ username }}
                {% endif %}
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-8 grid-margin stretch-card">
        <div class="card shadow">
          <div class="card-body">
            <div class="row">
              <div class="col-8">
                <h4 class="card-title">{% if nm_arsip %} Revision {% else %} Register {% endif %} Document - {{ nm_dokumen|capfirst }}</h4>
                <p class="card-description">
                  Add class <code>.table-striped</code>{% for u in get_id %}{{ u.name }}{% endfor %}
                </p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <form class="forms-sample mb-3" method="post" autocomplete="off" enctype="multipart/form-data">
                  {% csrf_token %}

                  <input type="hidden" name="dokumen" value="{{ nm_dokumen }}">
                  <input type="hidden" name="departemen" value="{{ nm_departemen }}">

                  {% for key, value in list_label.items %}
                  <!-- # Get the names of the related labels -->
                    {% for u in nm_label %}
                      {% if u.name == key %}
                        {% if value.type != "file" %}
                        <div class="form-group">
                          <label for="{{ key }}">{{ value.label }}</label>
                          <input type="{{ value.type }}" class="form-control" id="{{ key }}" name="{{ key }}" placeholder="{{ value.label }}" required 
                          
                          {% for obj in archive_list %}
                            {% if value.label == "Document Title" %} value="{{ obj|get_field_value:key }}" readonly{% endif %}
                            {% if value.label == "Document ID" %} value="{{ obj|get_field_value:key }}" readonly{% endif %}
                          {% endfor %}

                          {% if value.label == "Document ID" %} value="{{ nma_inisial|upper }}." {% endif %}
                          >
                          <!-- <input type="{{ value.type }}" class="form-control" id="{{ key }}" name="{{ key }}" placeholder="{{ value.label }}" required
                          {% if value.label == "Revision No" %}value="00" readonly {% elif value.label == "Document Number" %} value="{{ nma_inisial|upper }}." {% endif %}> -->
                        </div>
                        {% else %}
                        <div class="form-group">
                          <label>{{ value.label }}</label>
                          <input type="file" name="{{ key }}" class="file-upload-default" accept="{{ value.extension }}" {% if value.label == "PDF File" %}onchange="displayPDF(this)"{% endif %} required>
                          <div class="input-group col-xs-12">
                            <input type="text" class="form-control file-upload-info" disabled placeholder="{{ value.label }}">
                            <span class="input-group-append">
                              <button class="file-upload-browse btn btn-primary" type="button">Browse</button>
                            </span>
                          </div>
                        </div>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  {% endfor %}
                  <button type="submit" class="btn btn-twitter mr-1">Upload</button>
                  <button type="button" class="btn btn-facebook" onclick="window.location.href = document.referrer;">Cancel</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4 grid-margin stretch-card">
        <div class="card shadow w-100">
          <div class="card-header">
            PDF Viewer
          </div>
          <div class="card-body d-flex justify-content-center align-items-center">
            <div id="pdf-viewer">
              <canvas id="pdf-canvas" alt="pdf"></canvas>
            </div>
          </div>
        </div>
      </div>
    
    </div>
  </div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js"></script>
<script>
    function displayPDF(input) {
        const file = input.files[0];
        if (file.type === "application/pdf") {
            const fileReader = new FileReader();
            fileReader.onload = function() {
                const pdfData = new Uint8Array(this.result);
                const loadingTask = pdfjsLib.getDocument({data: pdfData});
                loadingTask.promise.then(pdf => {
                    pdf.getPage(1).then(page => {
                        const viewport = page.getViewport({scale: 1.5});
                        const canvas = document.getElementById('pdf-canvas');
                        const context = canvas.getContext('2d');
                        canvas.height = viewport.height;
                        canvas.width = viewport.width;
                        const renderContext = {
                            canvasContext: context,
                            viewport: viewport
                        };
                        page.render(renderContext);
                    });
                });
            };
            fileReader.readAsArrayBuffer(file);
        } else {
            alert("Please select a valid PDF file.");
        }
    }
</script>
{% include 'DMSApp/Komponen/footer.html' %}

templates/DMSApp/CrudArsip/view.html
{% load static %}
{% load custom_filters %}

{% include 'DMSApp/Komponen/navbar.html' %}
<!-- partial -->
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">Document Management System</h3>
            <nav aria-label="breadcrumb rounded-0">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">Document</li>
                {% if nm_departemen %}
                <li class="breadcrumb-item active" aria-current="page">{{ nm_departemen|capfirst }}</li>
                {% endif %}
                <li class="breadcrumb-item active" aria-current="page">{% if nm_dokumen %}<a href='{% url 'arsip_view' %}?dept={{ nm_departemen|custom_slugify }}'>{% endif %}Category</a></li>
                {% if nm_dokumen %}
                <li class="breadcrumb-item active" aria-current="page">{{ nm_dokumen|capfirst }}</li>
                {% endif %}
              </ol>
            </nav>
          </div>
          {% if nm_dokumen %}
          <div class="col-12 col-xl-4">
            <div class="justify-content-end d-flex">
              <div class="dropdown flex-md-grow-1 flex-xl-grow-0">
               <button onclick="window.location.href='{% url 'arsip_create' %}?menu={{ nm_dokumen|custom_slugify }}&dept={{ nm_departemen|custom_slugify }}'" class="btn btn-primary btn-icon-text">
                  <i class="ti-plus btn-icon-prepend"></i>
                  Register
                </button>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    {% if not nm_dokumen %}
    <div class="row">
      {% for dl in departemen_list %}
        {% if dl.is_active %}
        <div class="col-xl-4 mb-4 stretch-card transparent">
          <button onclick="window.location.href='{% url 'arsip_view' %}?menu={{ dl.document|custom_slugify }}&dept={{ nm_departemen|custom_slugify }}'" 
          class="card card-dark-blue border-0 shadow">
              <div class="card-body">
                <p class="m-1">{{ dl.document|capfirst }}</p>
              </div>
            </button>
        </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    {% if nm_dokumen %}
    <div class="row">
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card shadow">
          <div class="card-body">

            <div class="row">
              <div class="col-8">
                <h4 class="card-title">List - {{ nm_dokumen }}</h4>
                <p class="card-description">
                  Add class <code>.table-striped</code>
                </p>
              </div>
            </div>
            
            <div class="table-responsive">
              <table id="example" class="table table-striped table-hover">
                <thead>
                  <tr>
                    {% for key, value in list_label.items %}
                    <!-- # Get the names of the related labels -->
                      {% for u in nm_label %}
                        {% if u.name == key %}
                          {% if value.type != "file" %}
                          <th>{{ value.label }}</th>
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                  {% for obj in arsip_list %}
                  <tr>
                    {% for key, value in list_label.items %}
                    <!-- # Get the names of the related labels -->
                      {% for u in nm_label %}
                        {% if u.name == key %}
                          {% if value.type != "file" %}
                            {% if value.label == "Document Title" %}
                            <td><a href="{% url 'arsip_list_detail' %}?menu={{ nm_dokumen|custom_slugify }}&dept={{ nm_departemen|custom_slugify }}&archive={{ obj|get_field_value:key|custom_slugify }}">{{ obj|get_field_value:key|capfirst }}</a></td>
                            {% else %}
                            <td>{{ obj|get_field_value:key }}</td>
                            {% endif %}
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                    {% endfor %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}

  </div>
{% include 'DMSApp/Komponen/footer.html' %}